services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: mykhailo95/dishbackend:v1.4
    ports:
      - "3002:3002"
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      SECRET_ACCESS_KEY: ${SECRET_ACCESS_KEY}
      CLIENT_URL: ${CLIENT_URL}
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      NG_APP_APU_URL: ${NG_APP_APU_URL}
    volumes:
      - .:/app
    depends_on:
      - backend

volumes:
  pgdata:
